volumes:
  pnpm-cache:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run dev
    environment:
      - TZ=Asia/Taipei
    working_dir: /app
    volumes:
      - ./:/app
      - pnpm-cache:/root/.pnpm-store
    ports:
      - '3000:3000'
