name: Build

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.vscode/**'
  # Allows you to call this workflow from other workflows
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
# https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#contents
permissions:
  checks: write
  contents: read
  id-token: write
  pull-requests: read
# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: 'Checkout main repository with app logic 🛎️'
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          #lfs: true
          #persist-credentials: false
          #submodules: false

      - name: '🍩 Setup PNPM <del>and install dependencies</del>'
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
          #run_install: |
            #- recursive: true
            #  args: [--frozen-lockfile, --ignore-scripts]

      - name: '🍓 Use Node.js'
        uses: actions/setup-node@v3
        with:
          # @see https://github.com/nodejs/release#release-schedule
          node-version-file: '.node_version'
          cache: 'pnpm'

      - name: '🍩 Install dependencies'
        run: pnpm install --prefer-offline --ignore-scripts

      - name: '🍏 Build SvelteKit app'
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build

      - name: '🍯 Upload build output'
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: |
            build/
          retention-days: 1

# @links:
# https://github.com/Snugug/blog/blob/main/.github/workflows/tbd-site.yml
# https://github.com/Th3S4mur41/mh-photography.com/tree/alpha/.github/workflows
# https://github.com/kiosion/kio.dev/blob/main/.github/workflows/svelte.yml
